#include "PolarH10Web.h"

namespace {
const char PAGE[] PROGMEM = R"HTML(<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Polar H10 ECG</title><style>
:root{color-scheme:dark;--bg:#0b1220;--card:#131d2f;--line:#263750;--text:#e6edf7;--muted:#91a3ba;--accent:#45e0a8;--danger:#ffb454}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,sans-serif}nav{display:flex;gap:1rem;padding:1rem;flex-wrap:wrap;background:#0f1929}nav a{color:#b8c7d9;text-decoration:none}main{max-width:1050px;margin:auto;padding:1rem}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:1rem;box-shadow:0 12px 35px #0004}.head,.metrics,.controls{display:flex;align-items:center;gap:.75rem;flex-wrap:wrap}.head{justify-content:space-between}.head h1{font-size:1.2rem;margin:0}.state{font-size:.8rem;color:var(--muted)}.dot{display:inline-block;width:.7rem;height:.7rem;border-radius:50%;background:#607089;margin-right:.35rem}.dot.on{background:var(--accent);box-shadow:0 0 10px var(--accent)}.metrics{margin:.8rem 0}.metric{min-width:105px}.metric strong{font-size:1.35rem}.metric span{display:block;color:var(--muted);font-size:.75rem}.scope{position:relative;height:min(52vh,430px);min-height:240px;border:1px solid var(--line);border-radius:9px;overflow:hidden;background:#08111d}canvas{display:block;width:100%;height:100%}.axis{position:absolute;top:.45rem;font-size:.72rem;color:var(--muted);pointer-events:none}.axis.min{left:.6rem}.axis.max{right:.6rem}.notice{position:absolute;inset:auto 0 .6rem;text-align:center;color:var(--danger);font-size:.8rem;opacity:0;transition:opacity .2s}.notice.show{opacity:1}.controls{margin-top:.85rem}button,select{border:1px solid #40536e;border-radius:7px;padding:.5rem .75rem;background:#1a2940;color:var(--text)}button.active{border-color:var(--accent);color:var(--accent)}button{cursor:pointer}.spacer{flex:1}details{margin-top:.8rem;color:var(--muted)}pre{white-space:pre-wrap;font-size:.76rem}@media(max-width:600px){main{padding:.6rem}.card{padding:.7rem}.scope{height:42vh}.metric{min-width:82px}}
</style></head><body><nav><a href="/">ProgHard Link</a><a href="/polar">Polar ECG</a><a href="/config">Configuration</a><a href="/diagnostics">Diagnostics</a></nav>
<main><section class="card"><div class="head"><h1>Polar H10 ECG</h1><div class="state"><i id="dot" class="dot"></i><span id="state">CONNEXION…</span></div></div>
<div class="metrics"><div class="metric"><strong id="bpm">--</strong><span>BPM</span></div><div class="metric"><strong id="rate">130</strong><span>Hz</span></div><div class="metric"><strong id="gapCount">0</strong><span>Gaps</span></div><div class="metric"><strong id="dropped">0</strong><span>BLE dropped</span></div></div>
<div class="scope"><canvas id="ecg"></canvas><span id="ymin" class="axis min">-- µV</span><span id="ymax" class="axis max">-- µV</span><div id="notice" class="notice">Signal interrompu</div></div>
<div class="controls"><button id="pause">Pause</button><button data-window="2">2 s</button><button class="active" data-window="5">5 s</button><button data-window="10">10 s</button><span class="spacer"></span><label>Échelle <select id="scale"><option value="auto">Auto</option><option value="500">±500 µV</option><option value="1000">±1000 µV</option><option value="2000">±2000 µV</option></select></label></div>
<details><summary>Diagnostic</summary><pre id="diag"></pre></details></section></main>
<script>
'use strict';
const MAX=1300,values=new Int32Array(MAX),times=new Float64Array(MAX);let head=0,size=0,windowSec=5,paused=false,lastBlock=0,blocks=0,duplicates=0,gaps=0,invalid=0,lastHttp=0,rate=130,origin=null,noticeTimer=0,scaleLo=-500,scaleHi=500;
const q=id=>document.getElementById(id),canvas=q('ecg'),ctx=canvas.getContext('2d');
function clearSignal(){head=0;size=0;origin=null}
function notify(text){q('notice').textContent=text;q('notice').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>q('notice').classList.remove('show'),2500)}
function push(value,time){values[head]=value;times[head]=time;head=(head+1)%MAX;if(size<MAX)size++}
function u64(view,offset){return view.getBigUint64(offset,true)}
function decode(buffer){const v=new DataView(buffer);if(v.byteLength<24||v.getUint16(0,true)!==0xec02||v.getUint8(2)!==1||v.getUint16(4,true)!==24)throw Error('response header');const responseGap=!!(v.getUint8(3)&1),count=v.getUint16(6,true);if(responseGap){gaps++;clearSignal();lastBlock=0;notify('Signal interrompu · reprise automatique')}let offset=24;for(let n=0;n<count;n++){if(offset+2>v.byteLength){invalid++;break}const length=v.getUint16(offset,true);offset+=2;if(length<32||offset+length>v.byteLength){invalid++;break}const end=offset+length;try{if(v.getUint16(offset,true)!==0xec01||v.getUint8(offset+2)!==1||v.getUint16(offset+30,true)!==32)throw Error();const flags=v.getUint8(offset+3),sequence=v.getUint32(offset+8,true),firstTs=u64(v,offset+16),blockRate=v.getUint16(offset+24,true),countSamples=v.getUint16(offset+26,true);if(length!==32+countSamples*4||!blockRate||countSamples>33)throw Error();if(flags&1){clearSignal();lastBlock=0;notify('Nouvelle session ECG')}if(sequence<=lastBlock){duplicates++;offset=end;continue}if(lastBlock&&sequence!==lastBlock+1){gaps++;clearSignal();notify('Bloc manquant · reprise automatique')}lastBlock=sequence;rate=blockRate;if(origin===null)origin=firstTs;const period=1000000000n/BigInt(rate);for(let i=0;i<countSamples;i++){const ts=firstTs+BigInt(i)*period;push(v.getInt32(offset+32+i*4,true),Number(ts-origin)/1e9)}blocks++}catch(e){invalid++}offset=end}if(offset!==v.byteLength)invalid++}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function poll(){while(true){if(paused||document.visibilityState!=='visible'){await sleep(500);continue}const started=performance.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000);try{const r=await fetch(`/api/polar/ecg/blocks?after=${lastBlock}&max=4`,{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);decode(await r.arrayBuffer())}catch(e){invalid++;notify('Réseau ECG indisponible')}finally{clearTimeout(timer);lastHttp=Math.round(performance.now()-started)}await sleep(Math.max(0,200-(performance.now()-started)))}}
let stateBusy=false;async function updateState(){if(stateBusy)return;stateBusy=true;try{const s=await fetch('/api/polar',{cache:'no-store'}).then(r=>r.json());q('bpm').textContent=s.heartRate??'--';q('rate').textContent=s.ecgSampleRate||130;q('dropped').textContent=s.ecgDropped??0;const on=s.connected&&s.ecgStreaming;q('dot').classList.toggle('on',on);q('state').textContent=on?'CONNECTÉ':'EN ATTENTE'}catch(e){q('state').textContent='HORS LIGNE'}finally{stateBusy=false}}
setInterval(updateState,1500);updateState();
function resize(){const dpr=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;ctx.setTransform(dpr,0,0,dpr,0,0)}}
function draw(){resize();const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#182a40';ctx.lineWidth=1;for(let i=1;i<10;i++){ctx.beginPath();ctx.moveTo(w*i/10,0);ctx.lineTo(w*i/10,h);ctx.stroke()}for(let i=1;i<6;i++){ctx.beginPath();ctx.moveTo(0,h*i/6);ctx.lineTo(w,h*i/6);ctx.stroke()}const visible=[];if(size){const latest=times[(head+MAX-1)%MAX],cut=latest-windowSec;for(let i=0;i<size;i++){const index=(head-size+i+MAX)%MAX;if(times[index]>=cut)visible.push(index)}}let lo=-500,hi=500;if(q('scale').value==='auto'&&visible.length){lo=Infinity;hi=-Infinity;for(const i of visible){lo=Math.min(lo,values[i]);hi=Math.max(hi,values[i])}const margin=Math.max(50,(hi-lo)*.12);lo-=margin;hi+=margin;scaleLo=scaleLo*.85+lo*.15;scaleHi=scaleHi*.85+hi*.15;lo=scaleLo;hi=scaleHi}else if(q('scale').value!=='auto'){hi=Number(q('scale').value);lo=-hi;scaleLo=lo;scaleHi=hi}q('ymin').textContent=`${Math.round(lo)} µV`;q('ymax').textContent=`${Math.round(hi)} µV`;if(visible.length>1){const latest=times[visible[visible.length-1]],start=latest-windowSec;ctx.strokeStyle='#45e0a8';ctx.lineWidth=1.4;ctx.beginPath();visible.forEach((i,n)=>{const x=(times[i]-start)/windowSec*w,y=h-(values[i]-lo)/(hi-lo)*h;n?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}q('gapCount').textContent=gaps;q('diag').textContent=`lastBlockSequence: ${lastBlock}\nblocksReceived: ${blocks}\nduplicateBlocks: ${duplicates}\ngaps: ${gaps}\ninvalidBlocks/errors: ${invalid}\nlastHTTPms: ${lastHttp}\nbufferSamples: ${size}`;requestAnimationFrame(draw)}
q('pause').onclick=()=>{paused=!paused;q('pause').textContent=paused?'Reprendre':'Pause';q('pause').classList.toggle('active',paused)};document.querySelectorAll('[data-window]').forEach(b=>b.onclick=()=>{windowSec=Number(b.dataset.window);document.querySelectorAll('[data-window]').forEach(x=>x.classList.toggle('active',x===b))});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')notify('Reprise du signal')});
poll();requestAnimationFrame(draw);
</script></body></html>)HTML";
}

String PolarH10Web::page() { return FPSTR(PAGE); }
